### ISSUE TITLE
v0.1.0

### ISSUE THREAD

**Issue by 0x77dev** [0x77dev/ava#3]
## TODO

- [ ] Move to monorepo
- [ ] Create a web interface
  - [ ] Create documentation using Docus
- [ ] Add more examples like weather
- [ ] Add adapters for other platforms (Telegram, Discord, Slack, etc.)
- [ ] Ship in a Docker container
- [ ] Add conversation history store and context for GPT-3.0
- [ ] Add multi language support (DeepL API middleware)
- [ ] Add user profiles and user groups
  - [ ] RBAC on top of groups and limit VM/GPT-3 context based on user group
- [ ] Allow user to add custom extensions and personalize Ava
